### PR TITLE
Fix to render  in_progress events

### LINKED ISSUE #171: Create 'in_progress' events section of userhome

### PR DESCRIPTION
**Pull request by pckilgore**
This stuff is so related to @brenmeyer2245's single event page work on #111 that I just didn't spend much time on it looking nice.  I think we are going to render these buttons very differently very soon and that code will just be stripped out of the user-home component and moved to a SingleEvent component.

Regardless, the in_progress events now render on user-home.

closes #171 
needed by #111

### CODE REVIEW

File: client/components/user-home/cardAdminTools.js [hunk 1]
```diff
@@ -7,9 +7,14 @@ const CardAdminTools = ({id, type}) => {
...
   return (
     <div className="card-action right-align">
-      <Link to={`/events/${id}/${actionName}`} className="deep-orange-text">
-        {actionName} Event
-      </Link>
+      {type === 'in_progress' && (
+        <Link to={`/events/${id}/console`}>Go to Controller</Link>
+      )}
+      {type !== 'in_progress' && (
+        <Link to={`/events/${id}/${actionName}`} className="deep-orange-text">
```
Comment (brenmeyer2245) [inline client/components/user-home/cardAdminTools.js]: I actually just moved this to the single page
And replaced this with "Go to Event Details"
